# Generated by Django 5.2.14 on 2026-07-02 14:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_systemsettings_invoice_vault_slot_limit_per_project_chain"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="vault_slot_collect_min_worth_usd",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1"),
                help_text="归集计划到期执行时，槽位该币种余额价值低于该阈值则放弃本次归集（粉尘归集 gas 必亏；后续入账使总额达标后会再次调度）。0 表示不限制。",
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="VaultSlot 最小归集价值(USD)",
            ),
        ),
    ]
