# Generated by Codex on 2026-05-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tron", "0002_backfill_active_tron_usdt_watch_cursors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tronwatchcursor",
            name="last_safe_block",
        ),
    ]
