# Generated by Django 5.2.12 on 2026-05-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0013_delete_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addresschainstate",
            name="next_nonce",
        ),
    ]
